apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: nginx
spec:
  containers:
  - name: db
    image: quay.io/junkai/litmus:mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
  - name: wp
    image: quay.io/junkai/litmus:wordpress
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"