---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-admin
  namespace: litmus
  labels:
    name: litmus-admin
    app.kubernetes.io/part-of: litmus
---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding 
metadata:
  name: litmus-admin-binding
  namespace: litmus
  labels:
    name: litmus-admin
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: litmus-admin
  namespace: litmus

